#!/usr/bin/env python3
"""
SOMA-INTEL Phase 2 Step 2.3 — SOMA Bridge

Reads today's signals from soma_intel_signal + convergence beliefs and writes
digestible rows into soma.db for MANTIS and CIPHER consumption:

  raw_intelligence rows:
    - MANTIS batch   (source_type='soma_intel', target_pipeline='MANTIS')
      → all HIGH signals, structured for position-sizing / risk decisions
    - CIPHER batch   (source_type='soma_intel', target_pipeline='CIPHER')
      → convergence narratives + summary of top signals, structured for
        client-facing commentary

  events row:
    - event_type='SOMA_INTEL_DAILY_RUN'
      → run summary (signal counts, top tickers, convergence hits)

Idempotent: existing rows for (source_type='soma_intel', ingested_at date)
are skipped rather than duplicated.

Usage:
  python3 soma/intel/soma_intel_bridge.py           # dry run
  python3 soma/intel/soma_intel_bridge.py --apply   # write to soma.db
  python3 soma/intel/soma_intel_bridge.py --date 2026-05-04   # specific date
  python3 soma/intel/soma_intel_bridge.py --verbose
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from datetime import date, datetime, timezone
from pathlib import Path
from typing import Optional

# ── Path bootstrap ─────────────────────────────────────────────────────────────
_HERE    = Path(__file__).resolve().parent
_DABEIBA = _HERE.parent.parent.parent
for _p in [str(_DABEIBA), str(_DABEIBA / "shared")]:
    if _p not in sys.path:
        sys.path.insert(0, _p)

from soma.intel.store import IntelStore

# ── DB path (same soma.db for both sides of the bridge) ───────────────────────
DB_PATH = (
    Path(os.environ["SOMA_DB_PATH"])
    if "SOMA_DB_PATH" in os.environ
    else _DABEIBA / "shared" / "soma" / "data" / "soma.db"
)

VERSION = "soma-intel-bridge-v1"

# ── Priority filter — what goes to MANTIS vs CIPHER ───────────────────────────
MANTIS_PRIORITIES  = {"HIGH"}          # actionable → position-sizing
CIPHER_PRIORITIES  = {"HIGH", "MEDIUM"}  # narrative-worthy → commentary
MIN_ANOMALY_CIPHER = 0.15              # filter out near-zero MEDIUM signals


# ══════════════════════════════════════════════════════════════════════════════
# Signal readers
# ══════════════════════════════════════════════════════════════════════════════

def _read_signals(conn, target_date: str) -> list[dict]:
    """All active soma_intel_signal rows for the given date."""
    rows = conn.execute(
        """
        SELECT ticker, date, priority, anomaly_score, features,
               corroboration_count, half_life_days, horizon, notes
        FROM soma_intel_signal
        WHERE date = ? AND status != 'expired'
        ORDER BY anomaly_score DESC
        """,
        (target_date,),
    ).fetchall()
    out = []
    for r in rows:
        d = dict(r)
        try:
            d["features"] = json.loads(d["features"] or "{}")
        except (ValueError, TypeError):
            d["features"] = {}
        out.append(d)
    return out


def _read_convergence_beliefs(conn) -> list[dict]:
    """Active platform_count beliefs for multi-platform companies."""
    rows = conn.execute(
        """
        SELECT b.subject_node_id, b.value, b.confidence
        FROM soma_intel_belief b
        WHERE b.predicate = 'platform_count'
          AND b.superseded_by IS NULL
          AND CAST(b.value AS INTEGER) >= 2
        ORDER BY CAST(b.value AS INTEGER) DESC
        """,
    ).fetchall()
    return [dict(r) for r in rows]


def _read_top_beliefs(conn, limit: int = 10) -> list[dict]:
    """Top signal_score beliefs by confidence."""
    rows = conn.execute(
        """
        SELECT b.subject_node_id, b.value, b.confidence
        FROM soma_intel_belief b
        WHERE b.predicate = 'signal_score'
          AND b.superseded_by IS NULL
        ORDER BY CAST(b.value AS REAL) DESC
        LIMIT ?
        """,
        (limit,),
    ).fetchall()
    return [dict(r) for r in rows]


# ══════════════════════════════════════════════════════════════════════════════
# Content formatters
# ══════════════════════════════════════════════════════════════════════════════

def _format_mantis_content(
    signals: list[dict],
    convergence: list[dict],
    target_date: str,
) -> str:
    """
    Structured text for MANTIS consumption.
    Focus: which tickers have HIGH conviction + convergence status.
    """
    high_sigs = [s for s in signals if s["priority"] in MANTIS_PRIORITIES]

    lines = [
        f"SOMA-INTEL MANTIS BRIEF — {target_date}",
        f"Generated by soma_intel_bridge v1",
        "",
        f"HIGH-CONVICTION SIGNALS ({len(high_sigs)} tickers):",
    ]

    for s in high_sigs:
        feat   = s["features"]
        score  = feat.get("propagated_score") or feat.get("platform_count", "?")
        corr   = s["corroboration_count"]
        hl     = s["half_life_days"]
        is_conv = any(
            b["subject_node_id"] == f"co_{s['ticker']}"
            for b in convergence
        )
        conv_tag = " [CONVERGENCE]" if is_conv else ""
        lines.append(
            f"  {s['ticker']:<8} anomaly={s['anomaly_score']:.3f}"
            f"  score={score}  corr={corr}  hl={hl}d{conv_tag}"
        )

    lines += ["", f"PLATFORM CONVERGENCE ({len(convergence)} companies):"]
    for b in convergence:
        ticker  = b["subject_node_id"].replace("co_", "")
        n_plats = b["value"]
        lines.append(f"  {ticker}  platforms={n_plats}  conf={b['confidence']:.2f}")

    if not convergence:
        lines.append("  (none detected)")

    lines += [
        "",
        f"SIGNAL SUMMARY:",
        f"  Total signals today: {len(signals)}",
        f"  HIGH: {sum(1 for s in signals if s['priority']=='HIGH')}",
        f"  MEDIUM: {sum(1 for s in signals if s['priority']=='MEDIUM')}",
        f"  LOW: {sum(1 for s in signals if s['priority']=='LOW')}",
    ]

    return "\n".join(lines)


def _format_cipher_content(
    signals: list[dict],
    convergence: list[dict],
    top_beliefs: list[dict],
    target_date: str,
) -> str:
    """
    Narrative-ready text for CIPHER consumption.
    Focus: themes, convergence stories, commentary hooks.
    """
    cipher_sigs = [
        s for s in signals
        if s["priority"] in CIPHER_PRIORITIES
        and s["anomaly_score"] >= MIN_ANOMALY_CIPHER
    ]

    lines = [
        f"SOMA-INTEL CIPHER BRIEF — {target_date}",
        f"Generated by soma_intel_bridge v1",
        "",
        "SIGNAL INTELLIGENCE NARRATIVE:",
        "",
    ]

    # Convergence stories (highest narrative value)
    if convergence:
        lines.append("Platform Convergence Themes:")
        for b in convergence:
            ticker  = b["subject_node_id"].replace("co_", "")
            n_plats = int(b["value"])
            # Find convergence signal for this ticker
            conv_sig = next(
                (s for s in signals if s["ticker"] == ticker
                 and "convergence" in (s.get("notes") or "").lower()),
                None,
            )
            feat = conv_sig["features"] if conv_sig else {}
            pl_names = feat.get("platform_names", {})
            if pl_names:
                platform_str = ", ".join(pl_names.values())
            else:
                platform_str = f"{n_plats} platforms"
            lines.append(
                f"  {ticker} operates across {platform_str}. "
                f"Convergence across {n_plats} innovation platforms signals "
                f"structural positioning advantage."
            )
        lines.append("")

    # Top signals for commentary
    lines.append("Signal Leaders (narrative anchors):")
    for s in cipher_sigs[:10]:
        feat    = s["features"]
        score   = feat.get("propagated_score", "?")
        horizon = s.get("horizon", "medium")
        lines.append(
            f"  {s['ticker']:<8}  priority={s['priority']:<7}  "
            f"horizon={horizon}  anomaly={s['anomaly_score']:.3f}  score={score}"
        )
    if not cipher_sigs:
        lines.append("  (no signals above threshold today)")
    lines.append("")

    # Top belief scores
    lines.append("Top Signal-Score Beliefs:")
    for b in top_beliefs[:10]:
        ticker = b["subject_node_id"].replace("co_", "")
        lines.append(
            f"  {ticker:<8}  score={float(b['value']):.2f}  conf={b['confidence']:.3f}"
        )

    return "\n".join(lines)


def _format_event_details(
    signals: list[dict],
    convergence: list[dict],
    mantis_written: bool,
    cipher_written: bool,
) -> str:
    return json.dumps({
        "total_signals":      len(signals),
        "high_signals":       sum(1 for s in signals if s["priority"] == "HIGH"),
        "medium_signals":     sum(1 for s in signals if s["priority"] == "MEDIUM"),
        "low_signals":        sum(1 for s in signals if s["priority"] == "LOW"),
        "convergence_count":  len(convergence),
        "mantis_row_written": mantis_written,
        "cipher_row_written": cipher_written,
        "top_tickers":        [s["ticker"] for s in signals[:5]],
    })


# ══════════════════════════════════════════════════════════════════════════════
# DB writes
# ══════════════════════════════════════════════════════════════════════════════

def _already_written(conn, target_date: str, pipeline: str) -> bool:
    """Return True if a soma_intel raw_intelligence row exists for this date+pipeline."""
    row = conn.execute(
        """
        SELECT id FROM raw_intelligence
        WHERE source_type = 'soma_intel'
          AND target_pipeline = ?
          AND DATE(ingested_at) = ?
        LIMIT 1
        """,
        (pipeline, target_date),
    ).fetchone()
    return row is not None


def _write_raw_intel(
    conn,
    target_date: str,
    pipeline: str,
    title: str,
    content: str,
    category: str,
    relevance: int,
) -> int:
    """Insert a raw_intelligence row; returns the new row id."""
    cur = conn.execute(
        """
        INSERT INTO raw_intelligence
          (source_type, source_url, title, content, category,
           target_pipeline, relevance_score, key_claims_json,
           tags_json, ingested_at, processed, module_version)
        VALUES ('soma_intel', NULL, ?, ?, ?,
                ?, ?, NULL,
                ?, ?, 0, ?)
        """,
        (
            title,
            content,
            category,
            pipeline,
            relevance,
            json.dumps(["soma-intel", "signal", target_date]),
            datetime.now(timezone.utc).isoformat(),
            VERSION,
        ),
    )
    return cur.lastrowid


def _write_event(conn, target_date: str, details_json: str) -> None:
    conn.execute(
        """
        INSERT INTO events
          (date, event_type, source_module, details_json,
           write_timestamp, module_version)
        VALUES (?, 'SOMA_INTEL_DAILY_RUN', 'soma_intel_bridge', ?, ?, ?)
        """,
        (target_date, details_json,
         datetime.now(timezone.utc).isoformat(), VERSION),
    )


# ══════════════════════════════════════════════════════════════════════════════
# Main runner
# ══════════════════════════════════════════════════════════════════════════════

def run_bridge(
    target_date: str,
    dry_run: bool,
    verbose: bool,
) -> dict:
    stats = {
        "signals_found":    0,
        "convergence_hits": 0,
        "mantis_written":   False,
        "cipher_written":   False,
        "event_written":    False,
        "skipped_mantis":   False,
        "skipped_cipher":   False,
    }

    with IntelStore(db_path=DB_PATH) as store:
        conn = store._c  # reuse IntelStore's connection (same soma.db)

        signals     = _read_signals(conn, target_date)
        convergence = _read_convergence_beliefs(conn)
        top_beliefs = _read_top_beliefs(conn, limit=10)

        stats["signals_found"]    = len(signals)
        stats["convergence_hits"] = len(convergence)

        if verbose:
            print(f"  Signals found:     {len(signals)}")
            print(f"  Convergence hits:  {len(convergence)}")
            print(f"  Top beliefs:       {len(top_beliefs)}")

        # ── MANTIS row ─────────────────────────────────────────────────────
        if _already_written(conn, target_date, "MANTIS"):
            print("  [MANTIS] row already exists for today — skipping")
            stats["skipped_mantis"] = True
        else:
            mantis_content = _format_mantis_content(signals, convergence, target_date)
            high_count     = sum(1 for s in signals if s["priority"] == "HIGH")
            relevance      = min(10, max(5, 5 + high_count * 2))

            if verbose:
                print(f"\n  [MANTIS content preview]")
                for line in mantis_content.splitlines()[:12]:
                    print(f"    {line}")
                print("    ...")

            if not dry_run:
                _write_raw_intel(
                    conn,
                    target_date  = target_date,
                    pipeline     = "MANTIS",
                    title        = f"SOMA-INTEL Signal Brief {target_date}",
                    content      = mantis_content,
                    category     = "equities",
                    relevance    = relevance,
                )
                stats["mantis_written"] = True

        # ── CIPHER row ─────────────────────────────────────────────────────
        if _already_written(conn, target_date, "CIPHER"):
            print("  [CIPHER] row already exists for today — skipping")
            stats["skipped_cipher"] = True
        else:
            cipher_content = _format_cipher_content(
                signals, convergence, top_beliefs, target_date
            )
            conv_count  = len(convergence)
            relevance_c = min(10, max(4, 4 + conv_count * 3))

            if verbose:
                print(f"\n  [CIPHER content preview]")
                for line in cipher_content.splitlines()[:14]:
                    print(f"    {line}")
                print("    ...")

            if not dry_run:
                _write_raw_intel(
                    conn,
                    target_date  = target_date,
                    pipeline     = "CIPHER",
                    title        = f"SOMA-INTEL Narrative Brief {target_date}",
                    content      = cipher_content,
                    category     = "equities",
                    relevance    = relevance_c,
                )
                stats["cipher_written"] = True

        # ── events row ─────────────────────────────────────────────────────
        details = _format_event_details(
            signals, convergence,
            mantis_written = stats["mantis_written"],
            cipher_written = stats["cipher_written"],
        )
        if not dry_run:
            _write_event(conn, target_date, details)
            stats["event_written"] = True

        if not dry_run:
            conn.commit()

    return stats


# ══════════════════════════════════════════════════════════════════════════════
# Main
# ══════════════════════════════════════════════════════════════════════════════

def main() -> None:
    parser = argparse.ArgumentParser(
        description="SOMA-INTEL bridge — write daily signals to raw_intelligence + events"
    )
    parser.add_argument("--apply",   action="store_true",
                        help="Write to DB (default: dry run)")
    parser.add_argument("--date",    default=date.today().isoformat(), metavar="YYYY-MM-DD",
                        help="Target date for signal read (default: today)")
    parser.add_argument("--verbose", action="store_true")
    args = parser.parse_args()

    dry_run = not args.apply
    if dry_run:
        print("DRY RUN — pass --apply to write to DB\n")

    print(f"[SOMA-INTEL Bridge] date={args.date}")
    stats = run_bridge(
        target_date = args.date,
        dry_run     = dry_run,
        verbose     = args.verbose,
    )

    print(f"\n  Signals found:    {stats['signals_found']}")
    print(f"  Convergence hits: {stats['convergence_hits']}")
    print(f"  MANTIS row:       {'written' if stats['mantis_written'] else 'skipped' if stats['skipped_mantis'] else 'dry-run'}")
    print(f"  CIPHER row:       {'written' if stats['cipher_written'] else 'skipped' if stats['skipped_cipher'] else 'dry-run'}")
    print(f"  Event row:        {'written' if stats['event_written'] else 'dry-run'}")

    # DB snapshot
    with IntelStore(db_path=DB_PATH) as store:
        ri_count = store._c.execute(
            "SELECT COUNT(*) FROM raw_intelligence WHERE source_type='soma_intel'"
        ).fetchone()[0]
        ev_count = store._c.execute(
            "SELECT COUNT(*) FROM events WHERE event_type='SOMA_INTEL_DAILY_RUN'"
        ).fetchone()[0]
        print(f"\nDB snapshot:")
        print(f"  raw_intelligence (soma_intel):  {ri_count}")
        print(f"  events (SOMA_INTEL_DAILY_RUN):  {ev_count}")

    if dry_run:
        print("\nDRY RUN complete — pass --apply to write.")
    else:
        print("\nsoma_intel_bridge: OK")


if __name__ == "__main__":
    main()
